package edu.utexas.tacc.tapis.files.api.models;

import java.util.List;

import javax.validation.constraints.NotEmpty;

public class TransferTaskRequest {

	// Caller supplied tag returned in all events generated by this
	// transfer and any of its children.  Since this tag value is present
	// in all events, it can be used in Notification subscription filters.
	private String tag;
	
	private List<TransferTaskRequestElement> elements;

	@NotEmpty
    public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

    @NotEmpty
    public List<TransferTaskRequestElement> getElements() {
        return elements;
    }

    public void setElements(List<TransferTaskRequestElement> elements) {
        this.elements = elements;
    }
}
