docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWD"
    - git clone https://jmeiring:${CI_JOB_TOKEN}@gitlab.tacc.utexas.edu/tapis-project/tapis-shared-java.git
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_BRANCH" -f deploy/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$CI_BRANCH"
#  except:
#    - master
