cache:
  paths:
    - .m2/repository/

services:
  - docker:dind

stages:
  - compile
  - build-images

build:
  needs:
    - project: tapis-project/tapis-shared-java
      job: build
      artifacts: true

    # Official docker image.
  image: maven:3-openjdk-14
  stage: compile
  before_script:
    - yum install -y git
    - git clone -b dev https://${CI_DEPLOY_USER}:${CI_JOB_TOKEN}@gitlab.tacc.utexas.edu/tapis-project/tapis-shared-java.git
    - git clone -b dev https://${CI_DEPLOY_USER}:${CI_JOB_TOKEN}@gitlab.tacc.utexas.edu/tapis-project/tapis-client-java.git
    - git clone -b dev https://${CI_DEPLOY_USER}:${CI_JOB_TOKEN}@gitlab.tacc.utexas.edu/tapis-project/tapis-bom.git

  script:
    - mvn clean install -f tapis-bom/pom.xml
    - mvn clean install -f tapis-shared-java/pom.xml
    - mvn clean install -f tapis-client-java/pom.xml
    - mvn clean install -f tapis-files/pom.xml
#    - /usr/local/bin/docker push "$CI_REGISTRY_IMAGE:$CI_BRANCH"
#  except:
#    - master

