FROM rastasheep/ubuntu-sshd:18.04

COPY ./deploy/ssh-machine.pub /root/.ssh/authorized_keys

RUN mkdir -p /home/L1/L2/test2
RUN mkdir -p /home/L1/test1
COPY ./lib/src/test/resources/test1.txt /home/L1/L2/test2/test1.txt
