version: "3"

volumes:
  miniodata:
  files-pgdata:

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev
      - RABBITMQ_DEFAULT_VHOST=dev
    ports:
      - 5672:5672

  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DATABASE=dev
    volumes:
      - files-pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=user
      - MINIO_SECRET_KEY=password
    volumes:
      - miniodata:/data
    command: server /data

  irods:
    container_name: irods
    image: mjstealey/irods-provider-postgres:4.2.4
    ports:
      - 1247:1247

  ssh-machine:
    container_name: ssh-machine
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile.ssh-machine
    ports:
      - "2222:22"

  ssh-machine2:
    container_name: ssh2
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile.ssh-machine
    ports:
      - "2223:22"
    
    
   
