---
version: "3"

volumes:
  postgres-data:
  rabbitmq-data:
  minio-data:

networks:
  rabbitmq_netwrk:
    driver: bridge

services:
  postgres:
    image: postgres:11
    container_name: tapis-postgres
    labels:
      name: tapis-postgres
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DATABASE=dev
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8.11-management
    container_name: tapis-rabbitmq
    labels:
      name: tapis-rabbitmq
    environment:
      - HOSTNAME=localhost
      - RABBITMQ_DEFAULT_VHOST=dev
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - rabbitmq_netwrk

  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=user
      - MINIO_SECRET_KEY=password
    ports:
      - 9000:9000
    volumes:
      - minio-data:/data
    command: server /data

  irods:
    container_name: irods
    image: mjstealey/irods-provider-postgres:4.2.4
    ports:
      - 1247:1247

  ssh-machine:
    container_name: ssh-machine
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile.ssh-machine
    ports:
      - "2222:22"

  ssh-machine2:
    container_name: ssh2
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile.ssh-machine
    ports:
      - "2223:22"
