FROM openjdk:17-jdk-bullseye
WORKDIR /app
COPY lib/target ./lib/target/
WORKDIR /app/lib

# Java module commands that are always needed (java 17 and later).
ENV JAVA_MODULE_OPTS --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.time=ALL-UNNAMED \
                     --add-opens java.base/java.util=ALL-UNNAMED
EXPOSE 8080

CMD java -Xms4g -Xmx4g ${JAVA_MODULE_OPTS} -cp "target/tapis-files.jar:target/dependencies/*" edu.utexas.tacc.tapis.files.lib.transfers.TransfersApp