---
version: "3"

volumes:
  files-postgres-data:
  files-rabbitmq-data:

networks:
  rabbitmq_netwrk:
    driver: bridge

services:
  postgres:
    image: postgres:11
    container_name: tapis_files_postgres
    labels:
      name: tapis_files_postgres
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DATABASE=dev
    ports:
      - 5432:5432
    volumes:
      - files-postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8.11-management
    container_name: tapis-rabbitmq
    labels:
      name: tapis-rabbitmq
    environment:
      - HOSTNAME=localhost
      - RABBITMQ_DEFAULT_VHOST=dev
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - files-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - rabbitmq_netwrk
