# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: tapis-project/tapis-shared-java
        ref: dev
    - uses: actions/checkout@v2
      with:
        repository: tapis-project/tapis-bom
        ref: dev
    - uses: actions/checkout@v2
      with:
        repository: tapis-project/tapis-client-java
        ref: dev
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.3
      with:
        # Set the sonar.projectBaseDir analysis property
        projectBaseDir: # optional, default is .
    - name: Build with Maven
      run: |
        mvn install -f tapis-bom/pom.xml
        mvn install -f tapis-shared-java/pom.xml
        mvn install -f tapis-client-java/pom.xml
        mvn install -f tapis-files/pom.xml
